[metadata]
name = frolov_currencies
version = 1.0.0
author = Andrew Frolov
author_email = andrewfrolov76@gmail.com
description = Fetch Current Currencies from cbrf.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/bluv4nul/PROG5/lab2-pypi
classifiers =
    Programming Language :: Python
    License :: MS
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.0

[options.packages.find]
where = src